import type { Metadata } from "next";
import "../styles/globals.css";
import { Roboto } from 'next/font/google'
import Footer from "../components/Footer";
import Header from "../components/Header";

const roboto = Roboto({
  weight: ['100', '300', '400', "500", "700", "900"],
  subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
